### ISSUE TITLE
auro-badge: border on label variant should be brand-neutral-200

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-badge#12]
## Is your feature request related to a problem? Please describe.
Per @KyleJones2 and @designingcircles, the border color of the label variant should be auro-color-brand-neutral-200. It's currently brand-neutral-500

https://github.com/AlaskaAirlines/auro-badge/blob/be601b91cd46e2754b57cd5b5a29bdcb4bbdb6b7/src/style.scss#L138

## Describe the solution you'd like
Update the token used.

## Describe alternatives you've considered
n/a

## Additional context
This was discovered in the context of auro-flightline.

Once implemented, auro-flightline will need to update to the latest badge version.

**Comment by blackfalcon** [comment]
For how this color is being used, `auro-color-brand-neutral-200` fails all WCAG tests. This color should not be used for lines or type. It's meant for background treatments. 

![Screen Shot 2021-06-18 at 11 31 38 AM](https://user-images.githubusercontent.com/181089/122603194-dc67ee00-d028-11eb-91b3-dc68fd564fd7.png)

**Comment by blackfalcon** [comment]
The issue was with the design file. This issue is a `no-fix` and is closed.
