### ISSUE TITLE
Create blueprint figma file 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-badge#13]
# General Support Request

The auro-badge requires a blueprint supporting document to be released to Figma. The new element auro-slider has a dependency on this as a defined element for example use. 

## Support request

Review the current state of the auro-badge design and create the Figma blueprint document. 

## Possible Solution

Design to review current UI for new design opportunities.
Separating auro-badge and auro-tag due to functionality differences. This will not be reflected 1:1 on the dev and design side. Instead, the design toolkit will have two different components while development treats it as one component with different types.

## Exit criteria 

- [x] complete blueprint work
- [ ] signoff from Auro engineering (Dale Sande) https://github.com/AlaskaAirlines/auro-badge/issues/14
- [x] signoff from UI designers (Vidal Men) 
- [x] add link completed version of auro-badge blueprint ([Link](https://www.figma.com/file/mi7SCkpWH8lV3hv8SISZoc/Badge?node-id=322%3A298))
- [x] add link completed version of auro-tag blueprint ([Link](https://www.figma.com/file/41rmTiaZLRybunGsfrywwI/Tag?node-id=322%3A298))

## Next steps 

When this element blueprint is added to the Figma Auro UI Kit, this is intended to be used by the new auro-slider as an example.

- [ ] link new issues(s) from development plan to this design issue
- [ ] create new issue for the official release of the design blueprint (dependency on completed Auro component).

**Comment by leeejune** [comment]
[Completed blueprint in Figma](https://www.figma.com/file/mi7SCkpWH8lV3hv8SISZoc/Badge?node-id=322%3A298)

**Comment by leeejune** [comment]
@jason-capsule42 Requesting a dev review for the completed blueprint. Please let me know if there is anything to add/edit.

**Comment by leeejune** [comment]
@vidalmenAS Requesting a design review.

**Comment by blackfalcon** [comment]
This looks great. 

FYI others in this thread, it has been discussed that we will probably be deprecating the auro-badge component as it never really caught on and newer conversations around a more comprehensive auro-tag element are in progress. 

@leeejune regarding this element, one thing that has been an issue is how to deal with type descenders. E.g. a `y` or `g`. The type in this comp is always perfectly centered, but we can't actually recreate that in code because type and line height always account for descenders. This issue was raised by @erikalanghauser in regard to the use of auro-badge in the auro-flightline custom element. 

I just want to make sure that we are currently representing this in the blueprint.

**Comment by leeejune** [comment]
Would leaving a note be enough to reflect this? Or is there another preferred way to represent this?

**Comment by leeejune** [comment]
[Completed auro-tag blueprint](https://www.figma.com/file/41rmTiaZLRybunGsfrywwI/Tag?node-id=322%3A298)

**Comment by leeejune** [comment]
Added a note about type descenders.

**Comment by erikalanghauser** [comment]
Adding @ geoffcastroAAG to the thread.

**Comment by leeejune** [comment]
`auro-tag` will have a type called `auro-badge` to support different functionalities of "Tag" and "Badge" on the design side. On Figma, the two are distinct components. On the engineering side, they will be under the same web component `auro-tag`. Current `auro-badge`'s color features will be deprecated. The rest of the functions remain the same.

**Comment by vidalmenAS** [comment]
Reviewed + Approved!

**Comment by leeejune** [comment]
Added "Size" property to implement "Small" sized badge. Need @blackfalcon's review.

**Comment by blackfalcon** [comment]
@leeejun both large and small have the same definitions? Also, what is the border-radius? 


<img width="760" alt="Screen Shot 2021-10-20 at 3 26 01 PM" src="https://user-images.githubusercontent.com/181089/138181035-5e2b7132-5f21-4691-9c26-123b53d3bcbc.png">

**Comment by blackfalcon** [comment]
@leeejune feedback has been send via Teams for updates.

**Comment by leeejune** [comment]
@blackfalcon Changes made according to the feedback.

**Comment by blackfalcon** [comment]
This Blueprint file is complete and ready for dev plan.
