### ISSUE TITLE
auro-badge/tag: architectural discovery 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-badge#14]
# General Support Request

Design has produced a new concept regarding the auro-badge component. 

## Support request

- [x] review the new design and provide feedback as needed
  - [x] https://github.com/AlaskaAirlines/auro-badge/issues/13
- [ ] propose architectural direction for the development of a new element

## Completed Figam blueprints

- [x] Badge ([Link](https://www.figma.com/file/mi7SCkpWH8lV3hv8SISZoc/Badge?node-id=322%3A298))
- [x] Tag ([Link](https://www.figma.com/file/41rmTiaZLRybunGsfrywwI/Tag?node-id=322%3A298))

## Context

1. The current auro-badge element has come into question during the scope of the blueprint (https://github.com/AlaskaAirlines/auro-badge/issues/13) work. A working proposal is as follows: 

1. The current auro-badge is to be deprecated 
1. Development of a new auro-tag element is to be explored 
1. The auro-tag element will be a single element in engineering, but be considered individual things in design

**Comment by blackfalcon** [comment]
@leeejune is there an issue for tracking the blueprint work for Tag? https://www.figma.com/file/41rmTiaZLRybunGsfrywwI/Tag?node-id=322%3A298

**Comment by leeejune** [comment]
@blackfalcon It was attached to badge the whole time. No separate issue.

**Comment by blackfalcon** [comment]
I am pulling this out of the current project. It's not currently a priority.
