### ISSUE TITLE
auro-badge: custom color

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-badge#16]
## Is your feature request related to a problem? Please describe.
Some of our new designs feature a light green badge.  It's one of our design tokens but not a standard "error" or "success" color.

## Describe the solution you'd like
The ability to use any brand color needed for our designs

## Describe alternatives you've considered
Make a custom badge to match the design.

## Additional context
Perhaps following our current CustomColor attribute like we do in auro-icon

**Comment by geoffrich** [comment]
It seems to be possible with inline styles today. I'm not sure a custom attribute is necessary.

![image](https://user-images.githubusercontent.com/4992896/150196536-bdf6ddc7-3a91-4bc8-85f8-4f58f56bef7f.png)

```html
<auro-badge label="" style="color: blue; background-color: red; border-color: green;">Hello World</auro-badge>
```

**Comment by leeejune** [comment]
Added new preset values in blueprint: https://www.figma.com/file/mi7SCkpWH8lV3hv8SISZoc/Badge?node-id=322%3A298

**Comment by leeejune** [comment]
@braven112 Should I have a PR on this issue or should I create a different one for new preset colors?

**Comment by braven112** [comment]
Yeah go ahead and submit the PR.  I think we may also have to work in the repo upgrade somehow as well.
