### ISSUE TITLE
auro-badge: publish figma component

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-badge#18]
## Specific steps required to publish this component to Figma library and Auro doc site.

1. __Design & Planning__
    - [x] Blueprint is created #13 
1. __Development__
    - [ ] Sync with devs and get feedback and to make sure features in the blueprint match what will be developed in the first milestone.
    - [ ] Archive any features that will need to be part of a future version.
1. __Documentation__
      - [ ] Component properly described
      - [ ] Component use case(s) outlined
      - [ ] `Do Not` section outlines implementation scenarios to avoid
      - Example Section
        - [ ] Basic example of simplest use case
        - [ ] Work with dev to add other common use cases
        - [ ] Add figma instructions
        - [ ] Create release notes for new component
        - [ ] Add Figma tab and figma examples

1. __Publishing__
    - [ ] Publish component to figma library
    - [ ] Create PR for release on doc site

**Comment by Patrick-Daly-AA** [comment]
Figma component has been created, but it isn't on the doc site yet.
