### ISSUE TITLE
Create design documentation to differentiate badge and tag

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-badge#22]
# General Support Request

## Support request

Designers are confused about what the difference is between badge and tag.

## Possible Solution

Create documentation to explain how badge and tag will be separate on the design side vs categorized under badge on the engineering side.

**Comment by leeejune** [comment]
https://www.figma.com/file/mi7SCkpWH8lV3hv8SISZoc/Badge?node-id=0%3A810

Completed guidelines. Will share this during UI sync and design fair.

**Comment by jason-capsule42** [comment]
@leeejune @blackfalcon @braven112 This one hasn't changed in 17 days. What do we still need to do here?

**Comment by blackfalcon** [comment]
@jason-capsule42 it's waiting on me.

**Comment by blackfalcon** [comment]
@leeejune has final say in the design aspect of this work.
