### ISSUE TITLE
Node-sass and Orion Dependency Migration

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-badge#29]
# User story

There are multiple components that currently make use of this component, and when attempting to update to the newest auro design sass dependencies, we're seeing dependency tree conflicts due to node-sass and orion dependencies. 

![image](https://user-images.githubusercontent.com/25255197/218593348-d8775be0-e16b-464f-a941-b431fe6bd37a.png)

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- Migrate from orion to latest auro dependencies
- Migrate off of node-sass (I believe we're using dart-sass now?) 

## Definition of “Done” (exit criteria)

- There are no deprecated dependencies in the tree

**Comment by blackfalcon** [comment]
The complete scope of this work is being addressed with this milestone. 

https://github.com/AlaskaAirlines/auro-badge/milestone/3

**Comment by blackfalcon** [comment]
Addressed with latest release.
